// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-X4hPv4cBcBZADHjcGvgfuYWivbK8ow',
    appId: '1:777722286062:web:e1697647367f59420c08ff',
    messagingSenderId: '777722286062',
    projectId: 'armrboutique',
    authDomain: 'armrboutique.firebaseapp.com',
    storageBucket: 'armrboutique.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqoDD-mepxIVrtL1O0uznOg1jwV9-4rI',
    appId: '1:777722286062:android:44bbb51aaefca4300c08ff',
    messagingSenderId: '777722286062',
    projectId: 'armrboutique',
    storageBucket: 'armrboutique.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPRMNvhVG5n8m3rMloD4BBruIlEStx7Ko',
    appId: '1:777722286062:ios:c6e0a08117b9323d0c08ff',
    messagingSenderId: '777722286062',
    projectId: 'armrboutique',
    storageBucket: 'armrboutique.firebasestorage.app',
    iosBundleId: 'com.example.mrBoutique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPRMNvhVG5n8m3rMloD4BBruIlEStx7Ko',
    appId: '1:777722286062:ios:c6e0a08117b9323d0c08ff',
    messagingSenderId: '777722286062',
    projectId: 'armrboutique',
    storageBucket: 'armrboutique.firebasestorage.app',
    iosBundleId: 'com.example.mrBoutique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu-X4hPv4cBcBZADHjcGvgfuYWivbK8ow',
    appId: '1:777722286062:web:631ed08e7261723c0c08ff',
    messagingSenderId: '777722286062',
    projectId: 'armrboutique',
    authDomain: 'armrboutique.firebaseapp.com',
    storageBucket: 'armrboutique.firebasestorage.app',
  );
}
